### ISSUE TITLE
When I use the mod on my xbox copy I get a black screen

### ISSUE THREAD

**Issue by Fall08** [Faustas156/NeonLite#20]
![image](https://github.com/user-attachments/assets/3328aa84-0645-4777-828c-529e7dac40da)
Not sure if I'm doing this wrong, or if it just doesn't work with the gamepass version or something. I get that the mod was most likely not  intended for this version of the game. I just am hoping for the best lol. Please tell me it is my fault.

**Comment by Faustas156** [comment]
hey, neonlitev3 with gamepass is a little bit janky as of right now, however i have posted a pre-release build (provided by stxtic) in the releases section, which should work with xbox gamepass!

https://github.com/Faustas156/NeonLite/releases/tag/3.0-xbox
