### ISSUE TITLE
Canals Medal

### ISSUE THREAD

**Issue by Justlfied** [Faustas156/NeonLite#3]
Hello Mr. Faustas

The Canals medal of the Amethyst variety is way to high, can you please look into lowering it.

Your Sincere Regards,
Mike "Canals" Justlfied

**Comment by Faustas156** [comment]
L bozo

**Comment by steelLMG** [comment]
Hello Mr. Faustas

The Canals medal of the Amethyst Variety is way too  (completely fine), could you please look into (not doing anything)

Your Sincere Regards,
Idyll "Pummla" Canada
