### ISSUE TITLE
No Skip Intro setting

### ISSUE THREAD

**Issue by GelloMello** [Faustas156/NeonLite#7]
For some reason, I can't seem to find the 'Skip Intro' button in the settings. Even toggling on and off 'Disable Backstory' doesn't seem to work. Just wanted to know if I can keep the intro.

**Comment by Faustas156** [comment]
super sorry about the delay!! i'm hoping to add a change to it soon enough!! currently just unmotivated to work on stuff, but once i do, i will add it!! the intro gets automatically skipped and there is unfortunately no way to enable it once more

**Comment by Faustas156** [comment]
accidentally closed issue
